export default [
  {
    _id: '000001',
    position: { x: -40.08, y: 4.35, z: 4.75 },
    bindElementId: 4238,
    name: '光纤光栅传感器',
    company: '上海洛丁森工业自动化设备有限公司',
    automaticRenewal: true,
    installTime: 1572271123000,
    lastMaintenance: 1572341542000,
    status: 'running',
    price: 2000,
    personInCharge: '华晨宇',
    // url: 'https://us.wio.seeed.io/v1/node/GroveTempHumProD1/temperature?access_token=5d849a2515d6041082d9736b3925a334',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    _id: '000002',
    position: { x: 24.14, y: -9.20, z: 4.75 },
    bindElementId: 4262,
    name: '光纤光栅传感器',
    company: '西安安森智能仪器股份有限公司',
    automaticRenewal: false,
    installTime: 1550668914000,
    lastMaintenance: 1572341542000,
    status: 'running',
    price: 2000,
    personInCharge: '林书豪',
    // url: 'https://us.wio.seeed.io/v1/node/GroveTempHumProD0/humidity?access_token=5a4b75954f98ecc9905fc21a10bf36fa',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    _id: '000003',
    position: { x: -89.77, y: 23.25, z: 4.75 },
    bindElementId: 2655,
    name: '無線智能索力傳感器',
    company: '重庆川仪自动化股份有限公司',
    automaticRenewal: true,
    installTime: 1555168903000,
    lastMaintenance: 1572341542000,
    status: 'suspend',
    price: 4000,
    personInCharge: '陈飞',
    // url: 'https://us.wio.seeed.io/v1/node/GroveTempHumProD0/humidity?access_token=5a4b75954f98ecc9905fc21a10bf36fa',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
];
